alias ll='ls -l'
alias la='ls -al'
alias ..='cd ..'
alias md='mkdir -p'
alias rd='rm -rf'
alias grep='grep --color=auto'
alias psg='ps -e | grep'
alias c='clear'
alias h='history'
alias j='jobs -l'
alias cd..='cd ..'
alias ..='cd ..'

alias root='sudo su'

alias mvn='"/c/Program Files (x86)/insee/atelier-dev-2/applications/maven/bin/mvn.bat"'